FROM kolla/ubuntu-source-panko-base:7.0.5
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="panko-api" build-date="20191030"







COPY extend_start.sh /usr/local/bin/kolla_panko_extend_start
RUN chmod 755 /usr/local/bin/kolla_panko_extend_start


