FROM kolla/ubuntu-source-zun-base:7.0.5
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="zun-api" build-date="20191030"





COPY extend_start.sh /usr/local/bin/kolla_zun_extend_start
RUN chmod 755 /usr/local/bin/kolla_zun_extend_start


