FROM kolla/ubuntu-source-swift-base:7.0.5
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="swift-proxy-server" build-date="20191030"









RUN pip --no-cache-dir install --upgrade -c /requirements/upper-constraints.txt ceilometermiddleware






USER swift