FROM kolla/ubuntu-source-sahara-base:7.0.5
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="sahara-engine" build-date="20191030"






    
        
    


RUN apt-get update && apt-get -y install --no-install-recommends netcat && apt-get clean && rm -rf /var/lib/apt/lists/*




USER sahara