FROM kolla/ubuntu-source-vitrage-base:7.0.5
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="vitrage-api" build-date="20191030"








COPY extend_start.sh /usr/local/bin/kolla_vitrage_extend_start
RUN chmod 755 /usr/local/bin/kolla_vitrage_extend_start


